service: aws-zemoga-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
      role:
          statements:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - arn:aws:dynamodb:us-west-2:961288417686:table/UserTable
functions:
  createUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /users
          method: post
  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get
  updateUser:
    handler: src/updateUser.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put
  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
  getTweets:
    handler: src/tweets.tweetsByUserName
    events:
      - httpApi:
          path: /getTweets/{id}
          method: get

resources:
  Resources:
    UserTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH